<?php
namespace mod_valuemapdoc\event;

defined('MOODLE_INTERNAL') || die();

class document_saved extends \core\event\base {
    protected function init() {
        $this->data['crud'] = 'c';
        $this->data['edulevel'] = self::LEVEL_PARTICIPATING;
        $this->data['objecttable'] = 'valuemapdoc_documents';
    }

    public static function get_name() {
        return get_string('eventdocument_saved', 'mod_valuemapdoc');
    }

    public function get_description() {
        return "The user with id '{$this->userid}' saved a document generated by the Value Map Doc activity.";
    }

    public function get_url() {
        return new \moodle_url('/mod/valuemapdoc/view.php', ['id' => $this->contextinstanceid]);
    }
}
